unique_ids:
  assets:
    standard-page.html: CR3UCUIVBLZOGO6VKGDC2XTPRWDEJZX7
    theme.css: AWSUE7V2J3I5WTQJTV4QSSVG57SMF3XX
  forms:
    Form1: VORXGDDN4GGQWDBZEOTDWB3CVJT6EME3
  modules: {}
  scripts: {}
  server_modules: {}
